### ISSUE TITLE
Recommend installation with conda environment?

### ISSUE THREAD

**Issue by ewallace** [wassermanlab/TFFM#1]
I was able to get the TFFM tutorial to run using conda on Mac OS X. This might be helpful to add to the documentation.

First, [install conda and bioconda using the instructions](https://bioconda.github.io/user/install.html):

```
conda create --name tffm1 python=2.7 biopython=1.70 ghmm
```

This will require agreeing to install many packages, and takes a minute or two.

Activate the conda environment:

```
conda activate tffm
```

Download TFFM as a git repository:

```
git clone https://github.com/wassermanlab/TFFM.git
```

Change to tutorial directory and launch python:

```
cd TFFM/tutorial
python
```

Then proceed with the tutorial.

**Comment by amathelier** [comment]
Thanks so much for this! I've now incorporated it.
